// <auto-generated />
using System;
using Ecomweb.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ecomweb.Migrations
{
    [DbContext(typeof(EcomContext))]
    [Migration("20250908084647_UseDecimalInProduct")]
    partial class UseDecimalInProduct
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.25");

            modelBuilder.Entity("Ecomweb.Data.Cart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("UserId");

                    b.ToTable("Carts");
                });

            modelBuilder.Entity("ecomweb.Data.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Order");
                });

            modelBuilder.Entity("ecomweb.Data.OrderItems", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("OrderId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("PriceAtTime")
                        .HasColumnType("REAL");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("Ecomweb.Data.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            IsActive = false,
                            Name = "Chicken",
                            Price = 763.91305573617550m,
                            Quantity = 1
                        },
                        new
                        {
                            Id = 2,
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            IsActive = false,
                            Name = "Chips",
                            Price = 124.659435783718540m,
                            Quantity = 24
                        },
                        new
                        {
                            Id = 3,
                            Description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            IsActive = false,
                            Name = "Pants",
                            Price = 863.009126787459070m,
                            Quantity = 67
                        },
                        new
                        {
                            Id = 4,
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            IsActive = false,
                            Name = "Sausages",
                            Price = 923.170967699074480m,
                            Quantity = 38
                        },
                        new
                        {
                            Id = 5,
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            IsActive = false,
                            Name = "Chips",
                            Price = 511.836113273319550m,
                            Quantity = 88
                        },
                        new
                        {
                            Id = 6,
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            IsActive = false,
                            Name = "Sausages",
                            Price = 507.188042542413640m,
                            Quantity = 84
                        },
                        new
                        {
                            Id = 7,
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            IsActive = false,
                            Name = "Shoes",
                            Price = 453.079208636361550m,
                            Quantity = 32
                        },
                        new
                        {
                            Id = 8,
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            IsActive = false,
                            Name = "Table",
                            Price = 831.119924223964090m,
                            Quantity = 17
                        },
                        new
                        {
                            Id = 9,
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            IsActive = false,
                            Name = "Shirt",
                            Price = 239.936905441784530m,
                            Quantity = 3
                        },
                        new
                        {
                            Id = 10,
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            IsActive = false,
                            Name = "Hat",
                            Price = 353.317802291947450m,
                            Quantity = 10
                        },
                        new
                        {
                            Id = 11,
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            IsActive = false,
                            Name = "Hat",
                            Price = 624.826904784198040m,
                            Quantity = 69
                        },
                        new
                        {
                            Id = 12,
                            Description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            IsActive = false,
                            Name = "Sausages",
                            Price = 359.825160246946120m,
                            Quantity = 24
                        },
                        new
                        {
                            Id = 13,
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            IsActive = false,
                            Name = "Towels",
                            Price = 77.2318219254134860m,
                            Quantity = 47
                        },
                        new
                        {
                            Id = 14,
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            IsActive = false,
                            Name = "Chair",
                            Price = 347.165453792206270m,
                            Quantity = 23
                        },
                        new
                        {
                            Id = 15,
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            IsActive = false,
                            Name = "Sausages",
                            Price = 373.823895582387460m,
                            Quantity = 82
                        },
                        new
                        {
                            Id = 16,
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            IsActive = false,
                            Name = "Bike",
                            Price = 449.209915343919280m,
                            Quantity = 10
                        },
                        new
                        {
                            Id = 17,
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            IsActive = false,
                            Name = "Car",
                            Price = 92.6197154972223760m,
                            Quantity = 23
                        },
                        new
                        {
                            Id = 18,
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            IsActive = false,
                            Name = "Fish",
                            Price = 756.783508992516820m,
                            Quantity = 20
                        },
                        new
                        {
                            Id = 19,
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            IsActive = false,
                            Name = "Chair",
                            Price = 606.780906097629880m,
                            Quantity = 32
                        },
                        new
                        {
                            Id = 20,
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            IsActive = false,
                            Name = "Car",
                            Price = 382.098694382297740m,
                            Quantity = 88
                        },
                        new
                        {
                            Id = 21,
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            IsActive = false,
                            Name = "Salad",
                            Price = 112.582535657277610m,
                            Quantity = 67
                        },
                        new
                        {
                            Id = 22,
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            IsActive = false,
                            Name = "Cheese",
                            Price = 240.165159407036920m,
                            Quantity = 24
                        },
                        new
                        {
                            Id = 23,
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            IsActive = false,
                            Name = "Cheese",
                            Price = 255.824672934978280m,
                            Quantity = 53
                        },
                        new
                        {
                            Id = 24,
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            IsActive = false,
                            Name = "Shoes",
                            Price = 571.426433753161240m,
                            Quantity = 56
                        },
                        new
                        {
                            Id = 25,
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            IsActive = false,
                            Name = "Sausages",
                            Price = 70.8299473239945190m,
                            Quantity = 42
                        },
                        new
                        {
                            Id = 26,
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            IsActive = false,
                            Name = "Chair",
                            Price = 193.485860931503350m,
                            Quantity = 23
                        },
                        new
                        {
                            Id = 27,
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            IsActive = false,
                            Name = "Table",
                            Price = 607.947114781722970m,
                            Quantity = 96
                        },
                        new
                        {
                            Id = 28,
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            IsActive = false,
                            Name = "Computer",
                            Price = 738.906777936469990m,
                            Quantity = 7
                        },
                        new
                        {
                            Id = 29,
                            Description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            IsActive = false,
                            Name = "Soap",
                            Price = 509.595458615662420m,
                            Quantity = 60
                        },
                        new
                        {
                            Id = 30,
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            IsActive = false,
                            Name = "Soap",
                            Price = 533.344479987857770m,
                            Quantity = 10
                        },
                        new
                        {
                            Id = 31,
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            IsActive = false,
                            Name = "Pizza",
                            Price = 740.010637800773560m,
                            Quantity = 65
                        },
                        new
                        {
                            Id = 32,
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            IsActive = false,
                            Name = "Chicken",
                            Price = 360.180157575260980m,
                            Quantity = 13
                        },
                        new
                        {
                            Id = 33,
                            Description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            IsActive = false,
                            Name = "Shirt",
                            Price = 903.327134152225960m,
                            Quantity = 24
                        },
                        new
                        {
                            Id = 34,
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            IsActive = false,
                            Name = "Mouse",
                            Price = 742.154838588043750m,
                            Quantity = 2
                        },
                        new
                        {
                            Id = 35,
                            Description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            IsActive = false,
                            Name = "Keyboard",
                            Price = 676.352479238822530m,
                            Quantity = 41
                        },
                        new
                        {
                            Id = 36,
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            IsActive = false,
                            Name = "Fish",
                            Price = 283.354482918381040m,
                            Quantity = 20
                        },
                        new
                        {
                            Id = 37,
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            IsActive = false,
                            Name = "Car",
                            Price = 745.857224602748380m,
                            Quantity = 31
                        },
                        new
                        {
                            Id = 38,
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            IsActive = false,
                            Name = "Salad",
                            Price = 496.438981056274510m,
                            Quantity = 41
                        },
                        new
                        {
                            Id = 39,
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            IsActive = false,
                            Name = "Pizza",
                            Price = 390.086009132973220m,
                            Quantity = 40
                        },
                        new
                        {
                            Id = 40,
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            IsActive = false,
                            Name = "Pizza",
                            Price = 300.619517252489920m,
                            Quantity = 73
                        },
                        new
                        {
                            Id = 41,
                            Description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            IsActive = false,
                            Name = "Tuna",
                            Price = 775.969026690879550m,
                            Quantity = 71
                        },
                        new
                        {
                            Id = 42,
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            IsActive = false,
                            Name = "Pants",
                            Price = 272.270010221853040m,
                            Quantity = 97
                        },
                        new
                        {
                            Id = 43,
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            IsActive = false,
                            Name = "Bike",
                            Price = 408.398770269238420m,
                            Quantity = 35
                        },
                        new
                        {
                            Id = 44,
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            IsActive = false,
                            Name = "Shoes",
                            Price = 544.537985716511920m,
                            Quantity = 12
                        },
                        new
                        {
                            Id = 45,
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            IsActive = false,
                            Name = "Chips",
                            Price = 115.182451019783170m,
                            Quantity = 95
                        },
                        new
                        {
                            Id = 46,
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            IsActive = false,
                            Name = "Chair",
                            Price = 392.419530623282680m,
                            Quantity = 77
                        },
                        new
                        {
                            Id = 47,
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            IsActive = false,
                            Name = "Table",
                            Price = 753.148169969798890m,
                            Quantity = 83
                        },
                        new
                        {
                            Id = 48,
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            IsActive = false,
                            Name = "Hat",
                            Price = 91.777663245442780m,
                            Quantity = 32
                        },
                        new
                        {
                            Id = 49,
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            IsActive = false,
                            Name = "Bacon",
                            Price = 762.928904247606460m,
                            Quantity = 4
                        },
                        new
                        {
                            Id = 50,
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            IsActive = false,
                            Name = "Pizza",
                            Price = 912.19084370873920m,
                            Quantity = 68
                        });
                });

            modelBuilder.Entity("Ecomweb.Data.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("Salt")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Ecomweb.Data.Cart", b =>
                {
                    b.HasOne("Ecomweb.Data.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ecomweb.Data.User", null)
                        .WithMany("Carts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("ecomweb.Data.Order", b =>
                {
                    b.HasOne("Ecomweb.Data.User", null)
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ecomweb.Data.OrderItems", b =>
                {
                    b.HasOne("ecomweb.Data.Order", null)
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ecomweb.Data.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("ecomweb.Data.Order", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("Ecomweb.Data.User", b =>
                {
                    b.Navigation("Carts");

                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
