FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /source

# copy csproj and restore as distinct layers
COPY *.sln ./
COPY *.csproj Ecomweb/
WORKDIR /source/Ecomweb/
RUN dotnet restore 

# copy everything else and build app
COPY . ./Ecomweb/
WORKDIR /source/Ecomweb/
RUN dotnet publish -c release -o /app --no-restore

# final stage/image
FROM mcr.microsoft.com/dotnet/aspnet:8.0
EXPOSE 8508
WORKDIR /app
COPY --from=build /app ./
ENTRYPOINT ["dotnet", "Ecomweb.dll"]


# COPY Ecomweb/. .
# RUN dotnet publish --no-restore -o /Ecomweb
# EXPOSE 3000
